/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/abmelden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aktuelle Sitzung beenden
         * @description Abmelden.
         *
         *     Ohne Berechtigungsprüfung und ohne CSRF-Token: Abmelden ist immer erlaubt und darf auch mit
         *     einer bereits ungültigen Sitzung nicht fehlschlagen – sonst bleibt ein Cookie im Browser, das
         *     niemand mehr loswird.
         */
        post: operations["abmelden"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/anmelden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mit E-Mail und Passwort anmelden */
        post: operations["anmelden"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sicherheitsschlüssel der Sitzung abrufen
         * @description Token nachladen, falls die Oberfläche es verloren hat (nach einem Neuladen der Seite).
         */
        get: operations["csrf_token_abrufen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/ich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Angemeldeten Nutzer samt Berechtigungen abrufen
         * @description Der erste Aufruf der Oberfläche nach dem Laden.
         *
         *     Absichtlich ohne Passwortwechselpflicht: die Oberfläche muss erfahren, dass ein Wechsel
         *     aussteht, um zur Passwortmaske führen zu können.
         */
        get: operations["angemeldeten_nutzer_abrufen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/passwort-aendern": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Eigenes Passwort ändern
         * @description Passwort ändern.
         *
         *     Beendet alle anderen Sitzungen des Nutzers: wer das alte Passwort kannte, soll nicht über eine
         *     offene Sitzung weiterarbeiten können. Die aufrufende Sitzung bleibt bestehen.
         */
        post: operations["passwort_aendern"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gesundheit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Antwortet, solange die Anwendung läuft */
        get: operations["gesundheit_abrufen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systemstatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datenstand und Hintergrundläufe abrufen */
        get: operations["systemstatus_abrufen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systemstatus/jobs/{job}/starten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hintergrundlauf von Hand starten
         * @description Einen Lauf sofort auslösen – für die Prüfung nach der Einrichtung und nach einer Störung.
         */
        post: operations["job_starten"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Abmeldung */
        Abmeldung: {
            /**
             * Abgemeldet
             * @default true
             */
            abgemeldet: boolean;
        };
        /**
         * AngemeldeterNutzer
         * @description Was die Oberfläche über den angemeldeten Nutzer wissen muss.
         */
        AngemeldeterNutzer: {
            /** Csrf Token */
            csrf_token: string;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Muss Passwort Wechseln */
            muss_passwort_wechseln: boolean;
            /** Name */
            name: string;
            /** Rechte */
            rechte: {
                [key: string]: string;
            };
            /** Rollen */
            rollen: string[];
            /**
             * Sitzung Laeuft Ab
             * Format: date-time
             */
            sitzung_laeuft_ab: string;
        };
        /**
         * AnmeldeDaten
         * @description Anmeldedaten.
         *
         *     Die Kennung wird bewusst nur oberflächlich geprüft (enthält ein @, hat Vor- und Nachteil) und
         *     nicht gegen die vollständigen Regeln für E-Mail-Adressen. Eine strenge Prüfung bräuchte ein
         *     weiteres Paket und würde in Grenzfällen gültige Firmenadressen abweisen; ob die Kennung
         *     stimmt, entscheidet ohnehin der Abgleich mit der Nutzertabelle.
         */
        AnmeldeDaten: {
            /**
             * Angemeldet Bleiben
             * @default false
             */
            angemeldet_bleiben: boolean;
            /** Email */
            email: string;
            /** Passwort */
            passwort: string;
        };
        /** Gesundheit */
        Gesundheit: {
            /** Datenbank */
            datenbank: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStartErgebnis */
        JobStartErgebnis: {
            /** Gestartet */
            gestartet: boolean;
            /** Job */
            job: string;
            /** Meldung */
            meldung: string;
        };
        /** JobStatus */
        JobStatus: {
            /** Ab Phase */
            ab_phase: number;
            /** Alter Stunden */
            alter_stunden?: number | null;
            /** Beschreibung */
            beschreibung: string;
            /** Bezeichnung */
            bezeichnung: string;
            /** Dauer Ms */
            dauer_ms?: number | null;
            /** Eingerichtet */
            eingerichtet: boolean;
            /** Letzter Erfolg */
            letzter_erfolg?: string | null;
            /** Letzter Lauf */
            letzter_lauf?: string | null;
            /** Meldung */
            meldung?: string | null;
            /** Schluessel */
            schluessel: string;
            /** Status */
            status: string;
            /** Text */
            text: string;
        };
        /** PasswortDaten */
        PasswortDaten: {
            /** Altes Passwort */
            altes_passwort: string;
            /** Neues Passwort */
            neues_passwort: string;
        };
        /**
         * Systemstatus
         * @description Der „Datenstand"-Block der Startseite.
         */
        Systemstatus: {
            /** Gesamtstatus */
            gesamtstatus: string;
            /** Hinweise */
            hinweise: string[];
            /** Jobs */
            jobs: components["schemas"]["JobStatus"][];
            /** Naechster Lauf */
            naechster_lauf?: string | null;
            /** Zeitplan Laeuft */
            zeitplan_laeuft: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    abmelden: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Abmeldung"];
                };
            };
        };
    };
    anmelden: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnmeldeDaten"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AngemeldeterNutzer"];
                };
            };
            /** @description E-Mail oder Passwort stimmt nicht */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Kennung ist nach mehreren Fehlversuchen zeitweise gesperrt */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    csrf_token_abrufen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    angemeldeten_nutzer_abrufen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AngemeldeterNutzer"];
                };
            };
            /** @description Nicht angemeldet oder Sitzung abgelaufen */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    passwort_aendern: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswortDaten"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AngemeldeterNutzer"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Das alte Passwort stimmt nicht */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Das neue Passwort erfüllt die Anforderungen nicht */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gesundheit_abrufen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gesundheit"];
                };
            };
        };
    };
    systemstatus_abrufen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Systemstatus"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung systemstatus.lesen fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    job_starten: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartErgebnis"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung admin.jobs fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unbekannter Job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Der Job ist in dieser Phase noch nicht eingerichtet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
