/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ansprechpartner/{partner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Ansprechpartner ändern */
        put: operations["ansprechpartnerAendern"];
        post?: never;
        /**
         * Ansprechpartner löschen
         * @description Ansprechpartner löschen.
         *
         *     Die einzige Löschroute im Leitstand. Begründung: an einem Ansprechpartner hängt kein Beleg
         *     und keine Buchung – er ist eine Kontaktnotiz. Kunden, Projekte und Belege werden dagegen nie
         *     gelöscht, sondern wechseln den Status (CLAUDE.md Regel 5). Der Name bleibt im
         *     Änderungsprotokoll, damit nachvollziehbar ist, wer wann entfernt wurde.
         */
        delete: operations["ansprechpartnerLoeschen"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/abmelden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aktuelle Sitzung beenden
         * @description Abmelden.
         *
         *     Ohne Berechtigungsprüfung und ohne CSRF-Token: Abmelden ist immer erlaubt und darf auch mit
         *     einer bereits ungültigen Sitzung nicht fehlschlagen – sonst bleibt ein Cookie im Browser, das
         *     niemand mehr loswird.
         */
        post: operations["abmelden"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/anmelden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mit E-Mail und Passwort anmelden */
        post: operations["anmelden"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sicherheitsschlüssel der Sitzung abrufen
         * @description Token nachladen, falls die Oberfläche es verloren hat (nach einem Neuladen der Seite).
         */
        get: operations["csrf_token_abrufen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/ich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Angemeldeten Nutzer samt Berechtigungen abrufen
         * @description Der erste Aufruf der Oberfläche nach dem Laden.
         *
         *     Absichtlich ohne Passwortwechselpflicht: die Oberfläche muss erfahren, dass ein Wechsel
         *     aussteht, um zur Passwortmaske führen zu können.
         */
        get: operations["angemeldeten_nutzer_abrufen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/passwort-aendern": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Eigenes Passwort ändern
         * @description Passwort ändern.
         *
         *     Beendet alle anderen Sitzungen des Nutzers: wer das alte Passwort kannte, soll nicht über eine
         *     offene Sitzung weiterarbeiten können. Die aufrufende Sitzung bleibt bestehen.
         */
        post: operations["passwort_aendern"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gesundheit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Antwortet, solange die Anwendung läuft */
        get: operations["gesundheit_abrufen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kunden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kunden suchen und blättern
         * @description Kundenliste. Standardmäßig nur aktive – inaktive sind Altbestand und stören beim Suchen.
         */
        get: operations["kundenListe"];
        put?: never;
        /**
         * Kunden anlegen
         * @description Neuen Kunden anlegen. Die Kundennummer vergibt der Nummernkreis (PLAN §3).
         */
        post: operations["kundeAnlegen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kunden/{kunde_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kunden mit Ansprechpartnern lesen */
        get: operations["kundeLesen"];
        /**
         * Kunden ändern
         * @description Kunden ändern, mit Konfliktprüfung gegen den gelesenen Stand.
         */
        put: operations["kundeAendern"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kunden/{kunde_id}/ansprechpartner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ansprechpartner eines Kunden */
        get: operations["ansprechpartnerListe"];
        put?: never;
        /** Ansprechpartner anlegen */
        post: operations["ansprechpartnerAnlegen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migration/stand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ob die Bestandsdaten schon übernommen wurden */
        get: operations["migrationStand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migration/uebernehmen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bestandsdaten übernehmen
         * @description Wendet die Entscheidungen der Maske an und schreibt in einer Transaktion.
         */
        post: operations["migrationUebernehmen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/migration/vorschau": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bestandsdateien lesen und Zuordnung vorschlagen
         * @description Liest beide Dateien und schlägt die Zuordnung vor. Schreibt nichts.
         */
        get: operations["migrationVorschau"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projekte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projekte filtern und blättern
         * @description Projektliste mit den Filtern aus design/Projektliste.dc.html.
         */
        get: operations["projekteListe"];
        put?: never;
        /**
         * Projekt anlegen
         * @description Neues Projekt. Die Projektnummer richtet sich nach dem Auftragsjahr (PLAN §3).
         */
        post: operations["projektAnlegen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projekte/projektleiter/uebersicht": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projektleiternamen und ihre Zuordnung */
        get: operations["projektleiterUebersicht"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projekte/projektleiter/zuordnen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Projektleiternamen Nutzerkonten zuordnen
         * @description Setzt ``pl_user_id`` für alle Projekte eines Namens.
         *
         *     Der Name bleibt stehen: er ist der Herkunftsnachweis aus der Teamliste. Wäre er
         *     überschrieben, ließe sich später nicht mehr prüfen, ob die Zuordnung stimmt.
         */
        put: operations["projektleiterZuordnen"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projekte/{projekt_nr}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projekt mit Meilensteinen und Zahlungsplan lesen */
        get: operations["projektLesen"];
        /** Projekt ändern */
        put: operations["projektAendern"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projekte/{projekt_nr}/meilensteine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Meilensteine eines Projekts setzen
         * @description Meilensteine als Ganzes setzen.
         *
         *     Übergeben wird der vollständige Stand, nicht einzelne Änderungen: die Zeitleiste im
         *     Projektdetail bearbeitet mehrere Schritte in einem Zug, und ein Aufruf je Häkchen würde
         *     zehn Anfragen und zehn Protokolleinträge für einen Vorgang erzeugen.
         *
         *     Typen, die nicht mitgeschickt werden, bleiben unverändert – gelöscht wird hier nichts.
         */
        put: operations["meilensteineSetzen"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systemstatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datenstand und Hintergrundläufe abrufen */
        get: operations["systemstatus_abrufen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/systemstatus/jobs/{job}/starten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hintergrundlauf von Hand starten
         * @description Einen Lauf sofort auslösen – für die Prüfung nach der Einrichtung und nach einer Störung.
         */
        post: operations["job_starten"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Abmeldung */
        Abmeldung: {
            /**
             * Abgemeldet
             * @default true
             */
            abgemeldet: boolean;
        };
        /**
         * AngemeldeterNutzer
         * @description Was die Oberfläche über den angemeldeten Nutzer wissen muss.
         */
        AngemeldeterNutzer: {
            /** Csrf Token */
            csrf_token: string;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Muss Passwort Wechseln */
            muss_passwort_wechseln: boolean;
            /** Name */
            name: string;
            /** Rechte */
            rechte: {
                [key: string]: string;
            };
            /** Rollen */
            rollen: string[];
            /**
             * Sitzung Laeuft Ab
             * Format: date-time
             */
            sitzung_laeuft_ab: string;
        };
        /**
         * AnmeldeDaten
         * @description Anmeldedaten.
         *
         *     Die Kennung wird bewusst nur oberflächlich geprüft (enthält ein @, hat Vor- und Nachteil) und
         *     nicht gegen die vollständigen Regeln für E-Mail-Adressen. Eine strenge Prüfung bräuchte ein
         *     weiteres Paket und würde in Grenzfällen gültige Firmenadressen abweisen; ob die Kennung
         *     stimmt, entscheidet ohnehin der Abgleich mit der Nutzertabelle.
         */
        AnmeldeDaten: {
            /**
             * Angemeldet Bleiben
             * @default false
             */
            angemeldet_bleiben: boolean;
            /** Email */
            email: string;
            /** Passwort */
            passwort: string;
        };
        /** AnsprechpartnerAendern */
        AnsprechpartnerAendern: {
            /** Bemerkung */
            bemerkung?: string | null;
            /** Email */
            email?: string | null;
            /** Funktion */
            funktion?: ("technik" | "kaufmaennisch" | "sonstig") | null;
            /** Name */
            name: string;
            /**
             * Stand
             * Format: date-time
             */
            stand: string;
            /** Telefon */
            telefon?: string | null;
        };
        /** AnsprechpartnerAntwort */
        AnsprechpartnerAntwort: {
            /** Bemerkung */
            bemerkung?: string | null;
            /** Email */
            email?: string | null;
            /** Funktion */
            funktion?: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Stand
             * Format: date-time
             */
            stand: string;
            /** Telefon */
            telefon?: string | null;
        };
        /** AnsprechpartnerEingabe */
        AnsprechpartnerEingabe: {
            /** Bemerkung */
            bemerkung?: string | null;
            /** Email */
            email?: string | null;
            /** Funktion */
            funktion?: ("technik" | "kaufmaennisch" | "sonstig") | null;
            /** Name */
            name: string;
            /** Telefon */
            telefon?: string | null;
        };
        /** BefundAntwort */
        BefundAntwort: {
            /** Datei */
            datei: string;
            /** Meldung */
            meldung: string;
            /** Schwere */
            schwere: string;
            /** Spalte */
            spalte: string;
            /** Wert */
            wert: string;
            /** Zeile */
            zeile: number;
        };
        /** Gesundheit */
        Gesundheit: {
            /** Datenbank */
            datenbank: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStartErgebnis */
        JobStartErgebnis: {
            /** Gestartet */
            gestartet: boolean;
            /** Job */
            job: string;
            /** Meldung */
            meldung: string;
        };
        /** JobStatus */
        JobStatus: {
            /** Ab Phase */
            ab_phase: number;
            /** Alter Stunden */
            alter_stunden?: number | null;
            /** Beschreibung */
            beschreibung: string;
            /** Bezeichnung */
            bezeichnung: string;
            /** Dauer Ms */
            dauer_ms?: number | null;
            /** Eingerichtet */
            eingerichtet: boolean;
            /** Letzter Erfolg */
            letzter_erfolg?: string | null;
            /** Letzter Lauf */
            letzter_lauf?: string | null;
            /** Meldung */
            meldung?: string | null;
            /** Schluessel */
            schluessel: string;
            /** Status */
            status: string;
            /** Text */
            text: string;
        };
        /** Konto */
        Konto: {
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * KundeAendern
         * @description Wie :class:`KundeEingabe`, zusätzlich der gelesene Stand für die Konfliktprüfung.
         */
        KundeAendern: {
            /** Bemerkung */
            bemerkung?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name: string;
            /** Ort */
            ort?: string | null;
            /** Plz */
            plz?: string | null;
            /**
             * Stand
             * Format: date-time
             */
            stand: string;
            /**
             * Status
             * @default aktiv
             * @enum {string}
             */
            status: "aktiv" | "inaktiv";
            /** Strasse */
            strasse?: string | null;
            /** Telefon */
            telefon?: string | null;
            /**
             * Typ
             * @default b2c
             * @enum {string}
             */
            typ: "b2b" | "b2c";
            /** Ust Id */
            ust_id?: string | null;
            /** Zahlungsziel Tage */
            zahlungsziel_tage?: number | null;
            /** Zusatz */
            zusatz?: string | null;
        };
        /** KundeAntwort */
        KundeAntwort: {
            /** Ansprechpartner */
            ansprechpartner?: components["schemas"]["AnsprechpartnerAntwort"][];
            /**
             * Anzahl Projekte
             * @default 0
             */
            anzahl_projekte: number;
            /** Bemerkung */
            bemerkung?: string | null;
            /** Email */
            email?: string | null;
            /** Id */
            id: number;
            /** Kunden Nr */
            kunden_nr: number;
            /** Name */
            name: string;
            /** Ort */
            ort?: string | null;
            /** Plz */
            plz?: string | null;
            /**
             * Stand
             * Format: date-time
             */
            stand: string;
            /** Status */
            status: string;
            /** Strasse */
            strasse?: string | null;
            /** Telefon */
            telefon?: string | null;
            /** Typ */
            typ: string;
            /** Ust Id */
            ust_id?: string | null;
            /** Zahlungsziel Tage */
            zahlungsziel_tage?: number | null;
            /** Zusatz */
            zusatz?: string | null;
        };
        /** KundeEingabe */
        KundeEingabe: {
            /** Bemerkung */
            bemerkung?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name: string;
            /** Ort */
            ort?: string | null;
            /** Plz */
            plz?: string | null;
            /**
             * Status
             * @default aktiv
             * @enum {string}
             */
            status: "aktiv" | "inaktiv";
            /** Strasse */
            strasse?: string | null;
            /** Telefon */
            telefon?: string | null;
            /**
             * Typ
             * @default b2c
             * @enum {string}
             */
            typ: "b2b" | "b2c";
            /** Ust Id */
            ust_id?: string | null;
            /** Zahlungsziel Tage */
            zahlungsziel_tage?: number | null;
            /** Zusatz */
            zusatz?: string | null;
        };
        /**
         * KundeZeile
         * @description Kunde in der Liste – nur, was in der Tabelle steht.
         */
        KundeZeile: {
            /** Anzahl Projekte */
            anzahl_projekte: number;
            /** Id */
            id: number;
            /** Kunden Nr */
            kunden_nr: number;
            /** Name */
            name: string;
            /** Ort */
            ort?: string | null;
            /** Status */
            status: string;
            /** Typ */
            typ: string;
            /** Zusatz */
            zusatz?: string | null;
        };
        /** KundenSeite */
        KundenSeite: {
            /** Anzahl */
            anzahl: number;
            /** Eintraege */
            eintraege: components["schemas"]["KundeZeile"][];
            /** Gesamt */
            gesamt: number;
            /** Versatz */
            versatz: number;
        };
        /** MeilensteinAntwort */
        MeilensteinAntwort: {
            /** Bemerkung */
            bemerkung?: string | null;
            /** Erledigt */
            erledigt?: boolean | null;
            /** Erledigt Am */
            erledigt_am?: string | null;
            /** Geplant Kw */
            geplant_kw?: string | null;
            /** Id */
            id: number;
            /**
             * Stand
             * Format: date-time
             */
            stand: string;
            /** Typ */
            typ: string;
        };
        /** MeilensteinEingabe */
        MeilensteinEingabe: {
            /** Bemerkung */
            bemerkung?: string | null;
            /** Erledigt */
            erledigt?: boolean | null;
            /** Erledigt Am */
            erledigt_am?: string | null;
            /** Geplant Kw */
            geplant_kw?: string | null;
            /**
             * Typ
             * @enum {string}
             */
            typ: "uebergabetermin" | "freigabe_planung" | "plan_erstellt" | "anmeldung_nb" | "mastr" | "fertigmeldung" | "zaehler" | "abnahme" | "montage_uk" | "montage_elektro" | "zaehlerschrank" | "lieferung_uk" | "lieferung_wr_pv" | "lieferung_wr_speicher" | "lieferung_speicher" | "lieferung_wallbox" | "montage" | "lieferung" | "inbetriebnahme";
        };
        /** PasswortDaten */
        PasswortDaten: {
            /** Altes Passwort */
            altes_passwort: string;
            /** Neues Passwort */
            neues_passwort: string;
        };
        /** ProjektAendern */
        ProjektAendern: {
            /** Ab Wert Netto */
            ab_wert_netto?: number | null;
            /** Anlagenart */
            anlagenart?: ("aufdach" | "aufdach_speicher" | "freiflaeche" | "speicher" | "ladestation" | "sonstig") | null;
            /** Auftrag Vom */
            auftrag_vom?: string | null;
            /** Bemerkung */
            bemerkung?: string | null;
            /** Bezeichnung */
            bezeichnung?: string | null;
            /** Kunde Id */
            kunde_id: number;
            /** Ladestation */
            ladestation?: string | null;
            /** Pl Name */
            pl_name?: string | null;
            /** Pl User Id */
            pl_user_id?: number | null;
            /** Pv Kwp */
            pv_kwp?: number | null;
            /** Speicher Kwh */
            speicher_kwh?: number | null;
            /** Speicher Typ */
            speicher_typ?: string | null;
            /**
             * Stand
             * Format: date-time
             */
            stand: string;
            /** Standort */
            standort?: string | null;
            /**
             * Status
             * @default beauftragt
             * @enum {string}
             */
            status: "angebot" | "beauftragt" | "in_bau" | "abgeschlossen" | "storniert";
            /**
             * Typ
             * @default projekt
             * @enum {string}
             */
            typ: "projekt" | "service";
            /**
             * Ust Kz
             * @default 19
             * @enum {string}
             */
            ust_kz: "19" | "0" | "13b" | "gemischt";
            /** Vertriebsweg */
            vertriebsweg?: string | null;
            /** Wr Typ */
            wr_typ?: string | null;
        };
        /** ProjektAntwort */
        ProjektAntwort: {
            /** Ab Wert Netto */
            ab_wert_netto?: number | null;
            /** Anlagenart */
            anlagenart?: string | null;
            /** Auftrag Vom */
            auftrag_vom?: string | null;
            /** Bemerkung */
            bemerkung?: string | null;
            /** Bezeichnung */
            bezeichnung?: string | null;
            /**
             * Darf Werte Sehen
             * @default false
             */
            darf_werte_sehen: boolean;
            /** Id */
            id: number;
            /** Kunde */
            kunde: string;
            /** Kunde Id */
            kunde_id: number;
            /** Ladestation */
            ladestation?: string | null;
            /** Meilensteine */
            meilensteine?: components["schemas"]["MeilensteinAntwort"][];
            /** Pl Name */
            pl_name?: string | null;
            /** Pl User Id */
            pl_user_id?: number | null;
            /** Projekt Nr */
            projekt_nr: number;
            /** Pv Kwp */
            pv_kwp?: number | null;
            /** Quelle Migration */
            quelle_migration?: string | null;
            /** Speicher Kwh */
            speicher_kwh?: number | null;
            /** Speicher Typ */
            speicher_typ?: string | null;
            /**
             * Stand
             * Format: date-time
             */
            stand: string;
            /** Standort */
            standort?: string | null;
            /** Status */
            status: string;
            /** Typ */
            typ: string;
            /** Ust Kz */
            ust_kz: string;
            /** Vertriebsweg */
            vertriebsweg?: string | null;
            /** Wr Typ */
            wr_typ?: string | null;
            /** Zahlungsplan */
            zahlungsplan?: components["schemas"]["ZahlungsplanZeile"][];
            /** Zahlungsplan Gestellt Summe */
            zahlungsplan_gestellt_summe?: number | null;
            /** Zahlungsplan Summe */
            zahlungsplan_summe?: number | null;
        };
        /** ProjektEingabe */
        ProjektEingabe: {
            /** Ab Wert Netto */
            ab_wert_netto?: number | null;
            /** Anlagenart */
            anlagenart?: ("aufdach" | "aufdach_speicher" | "freiflaeche" | "speicher" | "ladestation" | "sonstig") | null;
            /** Auftrag Vom */
            auftrag_vom?: string | null;
            /** Bemerkung */
            bemerkung?: string | null;
            /** Bezeichnung */
            bezeichnung?: string | null;
            /** Kunde Id */
            kunde_id: number;
            /** Ladestation */
            ladestation?: string | null;
            /** Pl Name */
            pl_name?: string | null;
            /** Pl User Id */
            pl_user_id?: number | null;
            /** Pv Kwp */
            pv_kwp?: number | null;
            /** Speicher Kwh */
            speicher_kwh?: number | null;
            /** Speicher Typ */
            speicher_typ?: string | null;
            /** Standort */
            standort?: string | null;
            /**
             * Status
             * @default beauftragt
             * @enum {string}
             */
            status: "angebot" | "beauftragt" | "in_bau" | "abgeschlossen" | "storniert";
            /**
             * Typ
             * @default projekt
             * @enum {string}
             */
            typ: "projekt" | "service";
            /**
             * Ust Kz
             * @default 19
             * @enum {string}
             */
            ust_kz: "19" | "0" | "13b" | "gemischt";
            /** Vertriebsweg */
            vertriebsweg?: string | null;
            /** Wr Typ */
            wr_typ?: string | null;
        };
        /**
         * ProjektKandidat
         * @description Ein Projekt der Teamliste, wie es in der Maske zur Auswahl steht.
         */
        ProjektKandidat: {
            /** Ab Wert Netto */
            ab_wert_netto?: number | null;
            /** Auftrag Vom */
            auftrag_vom?: string | null;
            /** Kunde */
            kunde: string;
            /** Ort */
            ort?: string | null;
            /** Pl Name */
            pl_name?: string | null;
            /** Pv Kwp */
            pv_kwp?: string | null;
            /** Zeile */
            zeile: number;
        };
        /**
         * ProjektZeile
         * @description Projekt in der Liste (design/Projektliste.dc.html).
         */
        ProjektZeile: {
            /** Ab Wert Netto */
            ab_wert_netto?: number | null;
            /** Anlagenart */
            anlagenart?: string | null;
            /** Auftrag Vom */
            auftrag_vom?: string | null;
            /** Bezeichnung */
            bezeichnung?: string | null;
            /** Id */
            id: number;
            /** Kunde */
            kunde: string;
            /** Kunde Id */
            kunde_id: number;
            /** Pl Name */
            pl_name?: string | null;
            /** Projekt Nr */
            projekt_nr: number;
            /** Pv Kwp */
            pv_kwp?: number | null;
            /** Speicher Kwh */
            speicher_kwh?: number | null;
            /** Standort */
            standort?: string | null;
            /** Status */
            status: string;
        };
        /** ProjekteSeite */
        ProjekteSeite: {
            /** Anzahl */
            anzahl: number;
            /** Auftragsvolumen */
            auftragsvolumen?: number | null;
            /** Eintraege */
            eintraege: components["schemas"]["ProjektZeile"][];
            /** Gesamt */
            gesamt: number;
            /** Jahre */
            jahre?: number[];
            /** Projektleiter */
            projektleiter?: string[];
            /** Versatz */
            versatz: number;
        };
        /** ProjektleiterErgebnis */
        ProjektleiterErgebnis: {
            /** Geaendert */
            geaendert: number;
            /** Meldung */
            meldung: string;
        };
        /**
         * ProjektleiterName
         * @description Ein Name aus der Teamliste und wie weit er zugeordnet ist.
         */
        ProjektleiterName: {
            /** Anzahl Projekte */
            anzahl_projekte: number;
            /**
             * Ohne Konto
             * @default 0
             */
            ohne_konto: number;
            /** Pl Name */
            pl_name: string;
            /** User Ids */
            user_ids?: number[];
        };
        /** ProjektleiterUebersicht */
        ProjektleiterUebersicht: {
            /** Konten */
            konten: components["schemas"]["Konto"][];
            /** Namen */
            namen: components["schemas"]["ProjektleiterName"][];
        };
        /**
         * ProjektleiterZuordnung
         * @description Name auf Konto; ``None`` löst die Zuordnung wieder.
         */
        ProjektleiterZuordnung: {
            /** Zuordnungen */
            zuordnungen: {
                [key: string]: number | null;
            };
        };
        /**
         * StandAntwort
         * @description Ob und wann übernommen wurde.
         */
        StandAntwort: {
            /** Beendet */
            beendet?: string | null;
            /** Dateien */
            dateien?: string | null;
            /** Ergebnis */
            ergebnis?: {
                [key: string]: unknown;
            } | null;
            /** Gestartet */
            gestartet?: string | null;
            /** Importlauf Id */
            importlauf_id?: number | null;
            /** Migriert */
            migriert: boolean;
            /** Status */
            status?: string | null;
        };
        /**
         * Systemstatus
         * @description Der „Datenstand"-Block der Startseite.
         */
        Systemstatus: {
            /** Gesamtstatus */
            gesamtstatus: string;
            /** Hinweise */
            hinweise: string[];
            /** Jobs */
            jobs: components["schemas"]["JobStatus"][];
            /** Naechster Lauf */
            naechster_lauf?: string | null;
            /** Zeitplan Laeuft */
            zeitplan_laeuft: boolean;
        };
        /** UebernahmeAnfrage */
        UebernahmeAnfrage: {
            /** Entscheidungen */
            entscheidungen?: {
                [key: string]: number | null;
            };
            /** Kennung */
            kennung: string;
            /**
             * Offene Zulassen
             * @default false
             */
            offene_zulassen: boolean;
        };
        /** UebernahmeAntwort */
        UebernahmeAntwort: {
            /** Ab Luecken */
            ab_luecken: {
                [key: string]: unknown;
            }[];
            /** Gewerk Abgeleitet */
            gewerk_abgeleitet: {
                [key: string]: unknown;
            }[];
            /** Importlauf Id */
            importlauf_id: number | null;
            /** Kunden */
            kunden: number;
            /** Meilensteine */
            meilensteine: number;
            /** Meldung */
            meldung: string;
            /** Nicht Uebernommen */
            nicht_uebernommen: {
                [key: string]: unknown;
            }[];
            /** Projekte */
            projekte: number;
            /** Projekte Ohne Auftragsjahr */
            projekte_ohne_auftragsjahr: number;
            /** Zahlungsplan */
            zahlungsplan: number;
            /** Zahlungsplan Gestellt */
            zahlungsplan_gestellt: number;
            /** Zahlungsplan Summe Netto */
            zahlungsplan_summe_netto: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VorschauAntwort */
        VorschauAntwort: {
            /** Befunde */
            befunde: components["schemas"]["BefundAntwort"][];
            /** Kandidaten */
            kandidaten: components["schemas"]["ProjektKandidat"][];
            /** Kennung */
            kennung: string;
            /** Kontrollsummen */
            kontrollsummen: {
                [key: string]: unknown;
            };
            /** Zuordnungen */
            zuordnungen: components["schemas"]["ZuordnungAntwort"][];
        };
        /** Vorschlag */
        Vorschlag: {
            /** Guete */
            guete: number;
            /** Kunde */
            kunde: string;
            /** Projekt Zeile */
            projekt_zeile: number;
        };
        /** ZahlungsplanZeile */
        ZahlungsplanZeile: {
            /** Art */
            art: string;
            /** Berechnet */
            berechnet: boolean;
            /** Betrag Netto */
            betrag_netto: number;
            /** Bezeichnung */
            bezeichnung: string;
            /** Gewerk */
            gewerk: string;
            /** Id */
            id: number;
            /** Migriert Gestellt */
            migriert_gestellt?: boolean | null;
            /** Plan Monat */
            plan_monat?: string | null;
            /** Pos Nr */
            pos_nr: number;
        };
        /**
         * ZuordnungAntwort
         * @description Ein Kunde der Auftragsliste mit dem Projekt, zu dem seine Zeilen gehören.
         */
        ZuordnungAntwort: {
            /** Art */
            art: string;
            /** Betrag Netto */
            betrag_netto: number;
            /** Kundenteil */
            kundenteil: string;
            /** Offen */
            offen: boolean;
            /** Projekt Zeile */
            projekt_zeile?: number | null;
            /** Vorschlaege */
            vorschlaege?: components["schemas"]["Vorschlag"][];
            /** Zeilen */
            zeilen: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ansprechpartnerAendern: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partner_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnsprechpartnerAendern"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnsprechpartnerAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung kunden.schreiben fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datensatz nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Der Datensatz wurde zwischenzeitlich geändert */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ansprechpartnerLoeschen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partner_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung kunden.schreiben fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datensatz nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Der Datensatz wurde zwischenzeitlich geändert */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abmelden: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Abmeldung"];
                };
            };
        };
    };
    anmelden: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnmeldeDaten"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AngemeldeterNutzer"];
                };
            };
            /** @description E-Mail oder Passwort stimmt nicht */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Kennung ist nach mehreren Fehlversuchen zeitweise gesperrt */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    csrf_token_abrufen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    angemeldeten_nutzer_abrufen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AngemeldeterNutzer"];
                };
            };
            /** @description Nicht angemeldet oder Sitzung abgelaufen */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    passwort_aendern: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswortDaten"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AngemeldeterNutzer"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Das alte Passwort stimmt nicht */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Das neue Passwort erfüllt die Anforderungen nicht */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gesundheit_abrufen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gesundheit"];
                };
            };
        };
    };
    kundenListe: {
        parameters: {
            query?: {
                /** @description Name, Ort oder Kundennummer; Umlaute beliebig */
                suche?: string;
                status?: "aktiv" | "inaktiv" | "alle";
                versatz?: number;
                anzahl?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KundenSeite"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung kunden.lesen fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kundeAnlegen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KundeEingabe"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KundeAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung kunden.schreiben fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datensatz nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Der Datensatz wurde zwischenzeitlich geändert */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kundeLesen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kunde_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KundeAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung kunden.lesen fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kunde nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kundeAendern: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kunde_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KundeAendern"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KundeAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung kunden.schreiben fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datensatz nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Der Datensatz wurde zwischenzeitlich geändert */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ansprechpartnerListe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kunde_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnsprechpartnerAntwort"][];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung kunden.lesen fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kunde nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ansprechpartnerAnlegen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kunde_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnsprechpartnerEingabe"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnsprechpartnerAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung kunden.schreiben fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Datensatz nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Der Datensatz wurde zwischenzeitlich geändert */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    migrationStand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung importe.ausfuehren fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    migrationUebernehmen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UebernahmeAnfrage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UebernahmeAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung importe.ausfuehren fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Schon übernommen, Dateien geändert oder Zuordnungen offen */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    migrationVorschau: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VorschauAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung importe.ausfuehren fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Kein Migrationsordner eingerichtet oder Blatt fehlt */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projekteListe: {
        parameters: {
            query?: {
                /** @description Kunde, Ort, Bezeichnung oder Projektnummer */
                suche?: string;
                /** @description Auftragsjahr aus der Projektnummer */
                jahr?: number | null;
                status?: string;
                projektleiter?: string;
                anlagenart?: string;
                versatz?: number;
                anzahl?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjekteSeite"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung projekte.lesen fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projektAnlegen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjektEingabe"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjektAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung projekte.schreiben fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projekt nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Das Projekt wurde zwischenzeitlich geändert */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projektleiterUebersicht: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjektleiterUebersicht"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung projekte.lesen fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projektleiterZuordnen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjektleiterZuordnung"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjektleiterErgebnis"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung projekte.schreiben fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projekt nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Das Projekt wurde zwischenzeitlich geändert */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projektLesen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projekt_nr: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjektAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung projekte.lesen fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projekt nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projektAendern: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projekt_nr: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjektAendern"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjektAntwort"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung projekte.schreiben fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projekt nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Das Projekt wurde zwischenzeitlich geändert */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meilensteineSetzen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projekt_nr: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeilensteinEingabe"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeilensteinAntwort"][];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung meilensteine.schreiben fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projekt nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    systemstatus_abrufen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Systemstatus"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung systemstatus.lesen fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    job_starten: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartErgebnis"];
                };
            };
            /** @description Nicht angemeldet */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Berechtigung admin.jobs fehlt */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unbekannter Job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Der Job ist in dieser Phase noch nicht eingerichtet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
